language: python
sudo: false
cache:
  directories:
  - eggs
  - downloads
python:
  - 2.7
env:
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3
  - PLONE_VERSION=5.0
  - PLONE_VERSION=5.1
matrix:
  fast_finish: true
addons:
  firefox: 45.8.0esr
before_install:
  - pip uninstall -y six
  - deactivate
  - virtualenv ~/virtualenv/pipenv
  - source ~/virtualenv/pipenv/bin/activate
  - pip install pipenv
  - deactivate
install:
  - sed -ie "s#test-4.x.cfg#test-$PLONE_VERSION.x.cfg#" travis.cfg
  - sed -ie "s#versions-$PLONE_VERSION.x#versions#" travis.cfg
  - ~/virtualenv/pipenv/bin/pipenv install --dev
  - ~/virtualenv/pipenv/bin/pipenv run buildout -c travis.cfg -N buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
  - ~/virtualenv/pipenv/bin/pipenv run buildout -c travis.cfg -N buildout:download-cache=downloads code-analysis:return-status-codes=True
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - firefox -v
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install coveralls
  - coveralls
notifications:
  email:
    - development@it-spir.it
