language: python
sudo: false
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
matrix:
  fast_finish: true
  include:
    - python: "2.7"
      env: PLONE_VERSION=4.3
    - python: "2.7"
      env: PLONE_VERSION=5.0
    - python: "2.7"
      env: PLONE_VERSION=5.1
    - python: "2.7"
      env: PLONE_VERSION=5.2
    - python: "3.6"
      env: PLONE_VERSION=5.2
    - python: "3.7"
      env: PLONE_VERSION=5.2
      dist: xenial
      sudo: true
  allow_failures:
    - python: "2.7"
      env: PLONE_VERSION=5.2
    - python: "3.6"
      env: PLONE_VERSION=5.2
    - python: "3.7"
      env: PLONE_VERSION=5.2
cache:
  pip: true
  directories:
  - eggs
  - downloads
before_install:
  - pip uninstall -y six
  - mkdir webdriver;
    wget https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip;
    unzip chromedriver_linux64.zip -d webdriver;
    export PATH=$PATH:$(pwd)/webdriver;
install:
  - sed -ie "s#test-5.x.cfg#test-$PLONE_VERSION.x.cfg#" travis.cfg
  - sed -ie "s#versions-$PLONE_VERSION.x#versions#" travis.cfg
  - pip install -r requirements.txt
  - buildout -c travis.cfg -N buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
  - buildout -c travis.cfg -N buildout:download-cache=downloads code-analysis:return-status-codes=True
before_script:
  - 'export DISPLAY=:99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sleep 3
script:
  - python --version 2> /dev/stdout | grep 3.6 || bin/code-analysis
  - bin/test --all
after_success:
  - bin/createcoverage
  - pip install coveralls
  - coveralls
notifications:
  email:
    - development@it-spir.it
